//practice error handling
//try catch finally throw
let number1 = 10;
let number2 = "p";

try {
  let result = number1 / number2;
  console.log(result);
} catch (e) {
  console.log("error ");
}
